"""
Django settings for ccspredictor project.

Generated by 'django-admin startproject' using Django 5.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""


import os
from pathlib import Path

SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')


BASE_DIR = Path(__file__).resolve().parent.parent

MEDIA_ROOT = BASE_DIR / 'media'
MEDIA_URL = '/media/'

# Build paths inside the project like this: BASE_DIR / 'subdir'.

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/
import logging

logging.basicConfig(
    level=logging.INFO,
    format='[%(asctime)s] %(levelname)s %(name)s: %(message)s',
    handlers=[
        logging.FileHandler("celery_tasks.log"),
        logging.StreamHandler()
    ]
)

logger = logging.getLogger(__name__)

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,   # تغییرش دادم تا لاگ نزنه
    'handlers': {
        'file': {
            'level': 'DEBUG',
            'class': 'logging.FileHandler',
            'filename': BASE_DIR / 'debug.log',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['file'],
            'level': 'DEBUG',
            'propagate': True,  # تغییرش دادم
        },
    },
}

CELERY_BROKER_URL = "redis://fastccs1-yqq-service:6379/0"  # در اینجا از Redis به عنوان پیام‌رسان استفاده شده
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'

SECRET_KEY = 'h4POa4K8XwfzSYlZjnbu'

DEBUG = True # تغییرش دادم

# تنظیمات Celery برای استفاده از Redis به عنوان بروکر
CELERY_BROKER_URL = "redis://fastccs1-yqq-service:6379/0"
CELERY_BROKER_PASSWORD = 'h4POa4K8XwfzSYlZjnbu'

# ALLOWED_HOSTS = ['fastccs.com', 'www.fastccs.com', 'https://fastccs.com' , 'fastccs.runflare.run', 'www.fastccs.runflare.run', 'https://www.fastccs.com']

# SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# True

# # دامنه‌های معتبر برای CSRF
# CSRF_TRUSTED_ORIGINS = [
#     'fastccs.com', 'www.fastccs.com', 'https://fastccs.com' , 'fastccs.runflare.run', 'www.fastccs.runflare.run', 'https://www.fastccs.com'
# ]

ALLOWED_HOSTS = [
    'fastccs.com',
    'www.fastccs.com',
    'fastccs.runflare.run',
    'www.fastccs.runflare.run',
]

CSRF_TRUSTED_ORIGINS = [
    'https://fastccs.com',
    'https://www.fastccs.com',
    'https://fastccs.runflare.run',
    'https://www.fastccs.runflare.run',
]

SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# SECURE_SSL_REDIRECT = True

# SESSION_COOKIE_SECURE = True
# CSRF_COOKIE_SECURE = True

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_recaptcha',
    #'debug_toolbar',
    
    
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
   # 'debug_toolbar.middleware.DebugToolbarMiddleware',
]

ROOT_URLCONF = 'ccspredictor.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR  / 'predictor' / 'templates'],  # Correct path
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'ccspredictor.wsgi.application'

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles') 
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
RECAPTCHA_PUBLIC_KEY = '6LfmxSMqAAAAAJ2nw6hUp_d_Mpvf4Brb-YaHfm_k'
RECAPTCHA_PRIVATE_KEY = '6LfmxSMqAAAAAFsEpVCNSu-NS4IQfJyYxbdLf7mo'

